[package]
name = "bpe_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "bpe_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
regex = "1"
fancy-regex = "0.14"
rustc-hash = "2"
